server:
  port: 8080
# 应用名称
spring:
  # 环境
  profiles:
    active: dev
  application:
    name: strive_day_DEMO

# 自定义配置变量
custom:
  # 配置
  config:
    # 日志
    log:
      # 关闭转换为json字符串
      closeConvertJson: false
      # redisUtil工具添加日志，true: 开启
      lockLogFlag: true
      # 请求版本号校验开启日志打印，true: 开启
      requestVersionLogFlag: true
      file:
        # 文件重命名日志
        fileReNameLogFlag: true
        # 文件合并日志
        fileMergeLogFlag: true
        # 文件图片处理日志
        fileImageLogFlag: true
      crawler:
        # 爬虫日志
        crawlerLogFlag: true
    # guava-retry 重试机制
    guava:
      retry:
        # 是否开启
        enabled: true
        # 重试次数
        attemptNumber: 3
#        duration: 50000 配置不支持
        # 等待时间（重试间隔等待策略） 单位: 毫秒
        waitStrategySleepTime: 500
        # 重试方法最大执行时间（超过则中断重试）单位: 毫秒
        limitDuration: 50002
        # 重试接口（配置接口会尝试重试/使用注解也行，注解优先）
        apis:
          - com.xgf.mvc.controller.GuavaRetryDemoController.testGuavaRetryBaseConfig
          - com.xgf.mvc.controller.GuavaRetryDemoController.testGuavaRetryBaseAnnotation
#          - com.xgf.file.FileUtil.downloadImgByUrl
    # 访问请求配置
    request:
      # 请求版本Map配置
      versionMap: "{'demoVersionConfig':'22.33.55', 'b':'22.33.66', 'c':'22.33.77', 'd':'22.33.88'}"

    # 爬虫配置
    crawler:
      # 属性
      properties:
        # 浏览器类型 chrome / ie / firefox / edge ...
        browserType: 'chrome'
        # 浏览器驱动路径 webdriver todo 自动获取
        webDriverPath: 'E:\\000common file\\driver\\browser\\chrome\\chromedriver.exe'
        # Server returned HTTP response code: 403 for URL（403 无权限），设置请求头 User-Agent 属性来模拟浏览器运行
        reqHeadParamUserAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'
        # 网页url集合，可以多个网址，支持通配符(暂时只支持数字，格式如：[1-100]），eg: xxx/yy[1-100]，解析之后就是 xxx/yy1 、 xxx/yy2、...、xxx/yy100
        webPageUrlList:
          - https://wall.alphacoders.com/by_sub_category.php?id=359802&name=Hi-Fi+Rush+Wallpapers
        # 本地下载路径
        downloadPath: 'F:\\wqq\\image22'

        # 图片
        img:
          # 图片格式（jpg/png等）
          format: 'jpg'
          # 图片路径前缀添加（eg: 网页相对路径 /xx/xx）
          urlPreAppend: ''
          # 不包括的图片路径集合
          excludeUrls:
            - https://static.alphacoders.com/wa/English-flag.png







